server.port=8089


spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=crudapidb;encrypt=true;trustServerCertificate=true
spring.datasource.username=root
spring.datasource.password=2896

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


storage.location=uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs